// <auto-generated />
using FitnessEquipment.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessEquipment.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessEquipment.Domain.Weights.Models.WeightItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kgs")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("WeightTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightTypeId");

                    b.ToTable("WeightItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dumbbells are a type of weight training equipment that consists of a short bar with weights attached to both ends. They are commonly used for strength training exercises that target specific muscle groups in the arms, chest, shoulders, and back.",
                            Kgs = 32.5m,
                            Materials = "SteelAndRubber",
                            Name = "Dumbells Hex Pro",
                            Price = 250m,
                            WeightTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dumbbells are a type of weight training equipment that consists of a short bar with weights attached to both ends. They are commonly used for strength training exercises that target specific muscle groups in the arms, chest, shoulders, and back.",
                            Kgs = 10m,
                            Materials = "SteelAndRubber",
                            Name = "Dumbells TPU Series",
                            Price = 90m,
                            WeightTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dumbbells are a type of weight training equipment that consists of a short bar with weights attached to both ends. They are commonly used for strength training exercises that target specific muscle groups in the arms, chest, shoulders, and back.",
                            Kgs = 15m,
                            Materials = "CastIron",
                            Name = "Adjustable dumbells",
                            Price = 120m,
                            WeightTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kettlebells are weights that resemble a cannonball with a handle. They are used for strength training, cardiovascular fitness, and flexibility exercises, making them a versatile and effective tool for fitness enthusiasts and athletes alike.",
                            Kgs = 40m,
                            Materials = "Steel",
                            Name = "Russian Kettlebell",
                            Price = 250m,
                            WeightTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kettlebells are weights that resemble a cannonball with a handle. They are used for strength training, cardiovascular fitness, and flexibility exercises, making them a versatile and effective tool for fitness enthusiasts and athletes alike.",
                            Kgs = 16m,
                            Materials = "Steel",
                            Name = "HQ Competition Kettlebell",
                            Price = 90m,
                            WeightTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kettlebells are weights that resemble a cannonball with a handle. They are used for strength training, cardiovascular fitness, and flexibility exercises, making them a versatile and effective tool for fitness enthusiasts and athletes alike.",
                            Kgs = 8m,
                            Materials = "SteelAndRubber",
                            Name = "Vinyl Kettlebell",
                            Price = 40m,
                            WeightTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Weight plates are circular discs made of various materials such as iron, steel or rubber, used for resistance training and weightlifting exercises. They come in different sizes and weights, and are attached to barbells and weight machines to increase resistance and challenge the muscles during workouts.",
                            Kgs = 10m,
                            Materials = "Steel",
                            Name = "ATX Bumper Plates",
                            Price = 200m,
                            WeightTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Weight plates are circular discs made of various materials such as iron, steel or rubber, used for resistance training and weightlifting exercises. They come in different sizes and weights, and are attached to barbells and weight machines to increase resistance and challenge the muscles during workouts.",
                            Kgs = 20m,
                            Materials = "Rubber",
                            Name = "ATX Color Splash Plates",
                            Price = 150m,
                            WeightTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Weight plates are circular discs made of various materials such as iron, steel or rubber, used for resistance training and weightlifting exercises. They come in different sizes and weights, and are attached to barbells and weight machines to increase resistance and challenge the muscles during workouts.",
                            Kgs = 2m,
                            Materials = "Steel",
                            Name = "ATX Fractional Plates",
                            Price = 50m,
                            WeightTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Barbells are long metal bars with sleeves at either end for holding weight plates, used for strength training and weightlifting exercises. They come in different lengths, weights, and designs, and are a fundamental tool for building strength, power, and muscular endurance.",
                            Kgs = 20m,
                            Materials = "CastIron",
                            Name = "ATX – XTP Raw Powerlifting Bar",
                            Price = 700m,
                            WeightTypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Barbells are long metal bars with sleeves at either end for holding weight plates, used for strength training and weightlifting exercises. They come in different lengths, weights, and designs, and are a fundamental tool for building strength, power, and muscular endurance.",
                            Kgs = 25m,
                            Materials = "Steel",
                            Name = "ATX Trap Bar XL",
                            Price = 300m,
                            WeightTypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Barbells are long metal bars with sleeves at either end for holding weight plates, used for strength training and weightlifting exercises. They come in different lengths, weights, and designs, and are a fundamental tool for building strength, power, and muscular endurance.",
                            Kgs = 12m,
                            Materials = "CastIron",
                            Name = "Curl SZ PRO Bar ATX",
                            Price = 150m,
                            WeightTypeId = 4
                        });
                });

            modelBuilder.Entity("FitnessEquipment.Domain.WeightsTypes.Models.WeightType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("WeightTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dumbbells are a highly effective tool for building strength and muscle mass due to their versatility and ability to target specific muscle groups. They offer a greater range of motion than other weight training equipment, allowing for more muscle fibers to be engaged during exercises. Additionally, their adjustable weight feature allows for easy progression as strength increases, making them a great choice for both beginners and experienced lifters.",
                            Name = "Dumbells"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kettlebells are an effective tool for building strength, endurance, and flexibility due to their unique shape and design. They allow for a wide range of dynamic movements that engage multiple muscle groups simultaneously, improving overall fitness and coordination. Kettlebells are also highly versatile and can be used for a variety of exercises, including swings, snatches, and Turkish get-ups, making them an excellent choice for anyone looking to challenge their body and take their workouts to the next level.",
                            Name = "Kettlebells"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Weight plates are circular metal discs that are used to add resistance to a barbell, dumbbell, or weight machine. They come in a variety of sizes and weights, allowing users to gradually increase resistance levels as their strength improves, making them a versatile and essential tool in strength training and fitness programs.",
                            Name = "Plates"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Training with barbells is highly effective for building strength and muscle mass due to their ability to provide heavy resistance and target multiple muscle groups simultaneously. Barbells allow for a variety of compound exercises, such as squats, deadlifts, and bench press, which engage a large number of muscle fibers and promote overall growth and development. Additionally, their ability to progressively overload allows for continued gains in strength and muscle size, making them a staple in many strength training programs.",
                            Name = "Barbells"
                        });
                });

            modelBuilder.Entity("FitnessEquipment.Domain.Weights.Models.WeightItem", b =>
                {
                    b.HasOne("FitnessEquipment.Domain.WeightsTypes.Models.WeightType", "Type")
                        .WithMany("WeightItems")
                        .HasForeignKey("WeightTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FitnessEquipment.Domain.WeightsTypes.Models.WeightType", b =>
                {
                    b.Navigation("WeightItems");
                });
#pragma warning restore 612, 618
        }
    }
}
